live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "GeistMono NF"
style = "Bold"

[font.bold_italic]
family = "GeistMono NF"
style = "Bold Italic"

[font.italic]
family = "GeistMono NF"
style = "Italic"

[font.normal]
family = "GeistMono NF"
style = "Regular"

[font.offset]
x = 1
y = 2

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = """
tmux new-session -A -D -s main
"""
key = "A"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1
startup_mode = "SimpleFullScreen"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
