import = [
  "~/.config/alacritty/alacritty.os.toml",
]

live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font.bold]
family = "GeistMono NF"
style = "Bold"

[font.bold_italic]
family = "GeistMono NF"
style = "Bold Italic"

[font.italic]
family = "GeistMono NF"
style = "Italic"

[font.normal]
family = "GeistMono NF"
style = "Regular"

[font.offset]
x = 1
y = 2

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
